import { useForm } from '@inertiajs/react';
import InputLabel from '@/Components/InputLabel';
import TextInput from '@/Components/TextInput';
import Select from '@/Components/UI/Select';
import Button from '@/Components/UI/Button';
import InputError from '@/Components/InputError';
import { DocumentTextIcon } from '@heroicons/react/24/outline';

export default function ReportCardSettings({ settings }) {
    const { data, setData, post, processing, errors } = useForm({
        report_card_template: settings.report_card_template || 'classic',
        report_card_color_theme: settings.report_card_color_theme || 'school_colors',
        report_card_show_attendance: settings.report_card_show_attendance ?? true,
        report_card_show_position: settings.report_card_show_position ?? true,
        report_card_show_class_average: settings.report_card_show_class_average ?? true,
        report_card_show_teacher_comment: settings.report_card_show_teacher_comment ?? true,
        report_card_show_principal_comment: settings.report_card_show_principal_comment ?? true,
        report_card_header_text: settings.report_card_header_text || 'STUDENT REPORT CARD',
        report_card_disclaimer: settings.report_card_disclaimer || 'This result is generated by the school management system and is subject to errors and omissions.',
        report_card_notable_attributes: settings.report_card_notable_attributes ?? false,
    });

    const handleSubmit = (e) => {
        e.preventDefault();
        post(route('admin.settings.update.report-card'), {
            preserveScroll: true,
        });
    };

    return (
        <div className="space-y-6">
            <div className="flex items-center space-x-3 mb-6">
                <DocumentTextIcon className="h-6 w-6 text-indigo-600" />
                <h3 className="text-lg font-medium text-gray-900">Report Card Configuration</h3>
            </div>

            <form onSubmit={handleSubmit} className="space-y-8">
                {/* Visual Style */}
                <div className="bg-gray-50 rounded-xl p-6 border border-gray-100">
                    <h4 className="text-md font-semibold text-gray-900 mb-4">Visual Style</h4>
                    <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
                        <div>
                            <InputLabel htmlFor="report_card_template" value="Template Style" />
                            <Select
                                id="report_card_template"
                                value={data.report_card_template}
                                onChange={(e) => setData('report_card_template', e.target.value)}
                                className="mt-1 block w-full"
                            >
                                <option value="classic">Classic (Clean & Simple)</option>
                                <option value="modern">Modern (Bold Headers)</option>
                                <option value="professional">Professional (Compact)</option>
                            </Select>
                            <InputError message={errors.report_card_template} className="mt-2" />
                        </div>

                        <div>
                            <InputLabel htmlFor="report_card_color_theme" value="Color Theme" />
                            <Select
                                id="report_card_color_theme"
                                value={data.report_card_color_theme}
                                onChange={(e) => setData('report_card_color_theme', e.target.value)}
                                className="mt-1 block w-full"
                            >
                                <option value="school_colors">Use School Brand Colors</option>
                                <option value="blue">Professional Blue</option>
                                <option value="green">Academic Green</option>
                                <option value="red">Bold Red</option>
                                <option value="grayscale">Black & White (Printer Friendly)</option>
                            </Select>
                            <InputError message={errors.report_card_color_theme} className="mt-2" />
                        </div>
                    </div>
                </div>

                {/* Content Visibility */}
                <div className="bg-gray-50 rounded-xl p-6 border border-gray-100">
                    <h4 className="text-md font-semibold text-gray-900 mb-4">Content Visibility</h4>
                    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
                        <label className="flex items-center space-x-3 p-3 bg-white rounded-lg border border-gray-200 cursor-pointer hover:bg-gray-50">
                            <input
                                type="checkbox"
                                checked={data.report_card_show_attendance}
                                onChange={(e) => setData('report_card_show_attendance', e.target.checked)}
                                className="rounded border-gray-300 text-indigo-600 shadow-sm focus:ring-indigo-500 h-5 w-5"
                            />
                            <span className="text-sm font-medium text-gray-700">Show Attendance</span>
                        </label>

                        <label className="flex items-center space-x-3 p-3 bg-white rounded-lg border border-gray-200 cursor-pointer hover:bg-gray-50">
                            <input
                                type="checkbox"
                                checked={data.report_card_show_position}
                                onChange={(e) => setData('report_card_show_position', e.target.checked)}
                                className="rounded border-gray-300 text-indigo-600 shadow-sm focus:ring-indigo-500 h-5 w-5"
                            />
                            <span className="text-sm font-medium text-gray-700">Show Class Position</span>
                        </label>

                        <label className="flex items-center space-x-3 p-3 bg-white rounded-lg border border-gray-200 cursor-pointer hover:bg-gray-50">
                            <input
                                type="checkbox"
                                checked={data.report_card_show_class_average}
                                onChange={(e) => setData('report_card_show_class_average', e.target.checked)}
                                className="rounded border-gray-300 text-indigo-600 shadow-sm focus:ring-indigo-500 h-5 w-5"
                            />
                            <span className="text-sm font-medium text-gray-700">Show Class Average</span>
                        </label>

                        <label className="flex items-center space-x-3 p-3 bg-white rounded-lg border border-gray-200 cursor-pointer hover:bg-gray-50">
                            <input
                                type="checkbox"
                                checked={data.report_card_show_teacher_comment}
                                onChange={(e) => setData('report_card_show_teacher_comment', e.target.checked)}
                                className="rounded border-gray-300 text-indigo-600 shadow-sm focus:ring-indigo-500 h-5 w-5"
                            />
                            <span className="text-sm font-medium text-gray-700">Show Teacher's Comment</span>
                        </label>

                        <label className="flex items-center space-x-3 p-3 bg-white rounded-lg border border-gray-200 cursor-pointer hover:bg-gray-50">
                            <input
                                type="checkbox"
                                checked={data.report_card_show_principal_comment}
                                onChange={(e) => setData('report_card_show_principal_comment', e.target.checked)}
                                className="rounded border-gray-300 text-indigo-600 shadow-sm focus:ring-indigo-500 h-5 w-5"
                            />
                            <span className="text-sm font-medium text-gray-700">Show Principal's Comment</span>
                        </label>

                        <label className="flex items-center space-x-3 p-3 bg-white rounded-lg border border-gray-200 cursor-pointer hover:bg-gray-50">
                            <input
                                type="checkbox"
                                checked={data.report_card_notable_attributes}
                                onChange={(e) => setData('report_card_notable_attributes', e.target.checked)}
                                className="rounded border-gray-300 text-indigo-600 shadow-sm focus:ring-indigo-500 h-5 w-5"
                            />
                            <span className="text-sm font-medium text-gray-700">Show Behavioral Attributes</span>
                        </label>
                    </div>
                </div>

                {/* Custom Text */}
                <div className="bg-gray-50 rounded-xl p-6 border border-gray-100">
                    <h4 className="text-md font-semibold text-gray-900 mb-4">Custom Text</h4>
                    <div className="space-y-4">
                        <div>
                            <InputLabel htmlFor="report_card_header_text" value="Header Title" />
                            <TextInput
                                id="report_card_header_text"
                                type="text"
                                value={data.report_card_header_text}
                                onChange={(e) => setData('report_card_header_text', e.target.value)}
                                className="mt-1 block w-full"
                                placeholder="e.g. END OF TERM REPORT"
                            />
                            <InputError message={errors.report_card_header_text} className="mt-2" />
                        </div>

                        <div>
                            <InputLabel htmlFor="report_card_disclaimer" value="Footer Disclaimer" />
                            <textarea
                                id="report_card_disclaimer"
                                value={data.report_card_disclaimer}
                                onChange={(e) => setData('report_card_disclaimer', e.target.value)}
                                rows={2}
                                className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                                placeholder="Text to appear at the very bottom of the report card"
                            />
                            <InputError message={errors.report_card_disclaimer} className="mt-2" />
                        </div>
                    </div>
                </div>

                <div className="flex justify-end">
                    <Button
                        type="submit"
                        disabled={processing}
                        variant="primary"
                    >
                        {processing ? 'Saving Changes...' : 'Save Report Card Settings'}
                    </Button>
                </div>
            </form>
        </div>
    );
}
