import { useForm } from '@inertiajs/react';
import InputLabel from '@/Components/InputLabel';
import TextInput from '@/Components/TextInput';
import Select from '@/Components/UI/Select';
import Button from '@/Components/UI/Button';
import InputError from '@/Components/InputError';
import { DocumentTextIcon, EyeIcon } from '@heroicons/react/24/outline';

export default function ReportCardSettings({ settings, appSettings }) {
    const { data, setData, post, processing, errors } = useForm({
        report_card_template: settings.report_card_template || 'classic',
        report_card_color_theme: settings.report_card_color_theme || 'school_colors',
        report_card_show_attendance: settings.report_card_show_attendance ?? true,
        report_card_show_position: settings.report_card_show_position ?? true,
        report_card_show_class_average: settings.report_card_show_class_average ?? true,
        report_card_show_teacher_comment: settings.report_card_show_teacher_comment ?? true,
        report_card_show_principal_comment: settings.report_card_show_principal_comment ?? true,
        report_card_header_text: settings.report_card_header_text || 'STUDENT REPORT CARD',
        report_card_disclaimer: settings.report_card_disclaimer || 'This result is generated by the school management system and is subject to errors and omissions.',
        report_card_notable_attributes: settings.report_card_notable_attributes ?? false,
        report_card_table_header_color: settings.report_card_table_header_color || '#1e40af',
        report_card_table_border_color: settings.report_card_table_border_color || '#e2e8f0',
    });

    const handleSubmit = (e) => {
        e.preventDefault();
        post(route('admin.settings.update.report-card'), {
            preserveScroll: true,
        });
    };

    // Get colors based on theme selection
    const getThemeColors = () => {
        switch (data.report_card_color_theme) {
            case 'blue':
                return { primary: '#1e40af', secondary: '#3b82f6' };
            case 'green':
                return { primary: '#166534', secondary: '#22c55e' };
            case 'red':
                return { primary: '#991b1b', secondary: '#ef4444' };
            case 'grayscale':
                return { primary: '#374151', secondary: '#6b7280' };
            default:
                return {
                    primary: appSettings?.school_primary_color || '#1e40af',
                    secondary: appSettings?.school_secondary_color || '#3b82f6'
                };
        }
    };

    const themeColors = getThemeColors();

    return (
        <div className="space-y-6">
            <div className="flex items-center space-x-3 mb-6">
                <DocumentTextIcon className="h-6 w-6 text-indigo-600" />
                <h3 className="text-lg font-medium text-gray-900">Report Card Configuration</h3>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                {/* Settings Form */}
                <form onSubmit={handleSubmit} className="space-y-6">
                    {/* Visual Style */}
                    <div className="bg-gray-50 rounded-xl p-5 border border-gray-100">
                        <h4 className="text-md font-semibold text-gray-900 mb-4">Visual Style</h4>
                        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                            <div>
                                <InputLabel htmlFor="report_card_template" value="Template Style" />
                                <Select
                                    id="report_card_template"
                                    value={data.report_card_template}
                                    onChange={(e) => setData('report_card_template', e.target.value)}
                                    className="mt-1 block w-full"
                                >
                                    <option value="classic">Classic (Clean & Simple)</option>
                                    <option value="modern">Modern (Bold Headers)</option>
                                    <option value="professional">Professional (Compact)</option>
                                </Select>
                                <InputError message={errors.report_card_template} className="mt-2" />
                            </div>

                            <div>
                                <InputLabel htmlFor="report_card_color_theme" value="Color Theme" />
                                <Select
                                    id="report_card_color_theme"
                                    value={data.report_card_color_theme}
                                    onChange={(e) => setData('report_card_color_theme', e.target.value)}
                                    className="mt-1 block w-full"
                                >
                                    <option value="school_colors">Use School Brand Colors</option>
                                    <option value="blue">Professional Blue</option>
                                    <option value="green">Academic Green</option>
                                    <option value="red">Bold Red</option>
                                    <option value="grayscale">Black & White (Printer Friendly)</option>
                                </Select>
                                <InputError message={errors.report_card_color_theme} className="mt-2" />
                            </div>
                        </div>

                        {/* Table Colors */}
                        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 mt-4">
                            <div>
                                <InputLabel htmlFor="report_card_table_header_color" value="Table Header Color" />
                                <div className="flex items-center mt-1 space-x-2">
                                    <input
                                        type="color"
                                        id="report_card_table_header_color"
                                        value={data.report_card_table_header_color}
                                        onChange={(e) => setData('report_card_table_header_color', e.target.value)}
                                        className="w-10 h-10 rounded cursor-pointer border border-gray-300"
                                    />
                                    <TextInput
                                        type="text"
                                        value={data.report_card_table_header_color}
                                        onChange={(e) => setData('report_card_table_header_color', e.target.value)}
                                        className="flex-1"
                                        placeholder="#1e40af"
                                    />
                                </div>
                                <InputError message={errors.report_card_table_header_color} className="mt-2" />
                            </div>

                            <div>
                                <InputLabel htmlFor="report_card_table_border_color" value="Table Border Color" />
                                <div className="flex items-center mt-1 space-x-2">
                                    <input
                                        type="color"
                                        id="report_card_table_border_color"
                                        value={data.report_card_table_border_color}
                                        onChange={(e) => setData('report_card_table_border_color', e.target.value)}
                                        className="w-10 h-10 rounded cursor-pointer border border-gray-300"
                                    />
                                    <TextInput
                                        type="text"
                                        value={data.report_card_table_border_color}
                                        onChange={(e) => setData('report_card_table_border_color', e.target.value)}
                                        className="flex-1"
                                        placeholder="#e2e8f0"
                                    />
                                </div>
                                <InputError message={errors.report_card_table_border_color} className="mt-2" />
                            </div>
                        </div>
                    </div>

                    {/* Content Visibility */}
                    <div className="bg-gray-50 rounded-xl p-5 border border-gray-100">
                        <h4 className="text-md font-semibold text-gray-900 mb-4">Content Visibility</h4>
                        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                            {[
                                { key: 'report_card_show_attendance', label: 'Show Attendance' },
                                { key: 'report_card_show_position', label: 'Show Class Position' },
                                { key: 'report_card_show_class_average', label: 'Show Class Average' },
                                { key: 'report_card_show_teacher_comment', label: "Show Teacher's Comment" },
                                { key: 'report_card_show_principal_comment', label: "Show Principal's Comment" },
                                { key: 'report_card_notable_attributes', label: 'Show Behavioral Attributes' },
                            ].map(({ key, label }) => (
                                <label key={key} className="flex items-center space-x-3 p-3 bg-white rounded-lg border border-gray-200 cursor-pointer hover:bg-gray-50">
                                    <input
                                        type="checkbox"
                                        checked={data[key]}
                                        onChange={(e) => setData(key, e.target.checked)}
                                        className="rounded border-gray-300 text-indigo-600 shadow-sm focus:ring-indigo-500 h-5 w-5"
                                    />
                                    <span className="text-sm font-medium text-gray-700">{label}</span>
                                </label>
                            ))}
                        </div>
                    </div>

                    {/* Custom Text */}
                    <div className="bg-gray-50 rounded-xl p-5 border border-gray-100">
                        <h4 className="text-md font-semibold text-gray-900 mb-4">Custom Text</h4>
                        <div className="space-y-4">
                            <div>
                                <InputLabel htmlFor="report_card_header_text" value="Header Title" />
                                <TextInput
                                    id="report_card_header_text"
                                    type="text"
                                    value={data.report_card_header_text}
                                    onChange={(e) => setData('report_card_header_text', e.target.value)}
                                    className="mt-1 block w-full"
                                    placeholder="e.g. END OF TERM REPORT"
                                />
                                <InputError message={errors.report_card_header_text} className="mt-2" />
                            </div>

                            <div>
                                <InputLabel htmlFor="report_card_disclaimer" value="Footer Disclaimer" />
                                <textarea
                                    id="report_card_disclaimer"
                                    value={data.report_card_disclaimer}
                                    onChange={(e) => setData('report_card_disclaimer', e.target.value)}
                                    rows={2}
                                    className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:border-indigo-500 focus:ring-indigo-500 text-sm"
                                    placeholder="Text to appear at the very bottom of the report card"
                                />
                                <InputError message={errors.report_card_disclaimer} className="mt-2" />
                            </div>
                        </div>
                    </div>

                    <div className="flex justify-end">
                        <Button
                            type="submit"
                            disabled={processing}
                            variant="primary"
                        >
                            {processing ? 'Saving Changes...' : 'Save Report Card Settings'}
                        </Button>
                    </div>
                </form>

                {/* Live Preview Panel */}
                <div className="bg-gray-50 rounded-xl p-5 border border-gray-100">
                    <div className="flex items-center space-x-2 mb-4">
                        <EyeIcon className="h-5 w-5 text-indigo-600" />
                        <h4 className="text-md font-semibold text-gray-900">Live Preview</h4>
                    </div>

                    {/* Mini Report Card Preview */}
                    <div className="bg-white rounded-lg shadow-sm p-4 border border-gray-200 transform scale-100 origin-top-left">
                        {/* Header */}
                        <div
                            className="rounded-t-lg p-3 text-center mb-3"
                            style={{
                                background: `linear-gradient(135deg, ${themeColors.primary} 0%, ${themeColors.secondary} 100%)`
                            }}
                        >
                            <div className="text-white">
                                <div className="font-bold text-sm">{appSettings?.school_name || 'Sample School Name'}</div>
                                <div className="text-xs opacity-90 mt-1">{data.report_card_header_text}</div>
                            </div>
                        </div>

                        {/* Student Info Preview */}
                        <div className="bg-gray-50 rounded p-2 mb-3 text-xs">
                            <div className="grid grid-cols-2 gap-1">
                                <div><span className="font-semibold text-gray-500">Name:</span> John Doe</div>
                                <div><span className="font-semibold text-gray-500">Class:</span> JSS 1A</div>
                                {data.report_card_show_position && (
                                    <div><span className="font-semibold text-gray-500">Position:</span> 3rd of 25</div>
                                )}
                                {data.report_card_show_attendance && (
                                    <div><span className="font-semibold text-gray-500">Attendance:</span> 95%</div>
                                )}
                            </div>
                        </div>

                        {/* Sample Table */}
                        <div className="mb-3">
                            <table className="w-full text-xs border-collapse">
                                <thead>
                                    <tr>
                                        <th
                                            className="p-2 text-left text-white font-semibold"
                                            style={{ backgroundColor: data.report_card_table_header_color }}
                                        >
                                            Subject
                                        </th>
                                        <th
                                            className="p-2 text-center text-white font-semibold"
                                            style={{ backgroundColor: data.report_card_table_header_color }}
                                        >
                                            Score
                                        </th>
                                        <th
                                            className="p-2 text-center text-white font-semibold"
                                            style={{ backgroundColor: data.report_card_table_header_color }}
                                        >
                                            Grade
                                        </th>
                                        {data.report_card_show_class_average && (
                                            <th
                                                className="p-2 text-center text-white font-semibold"
                                                style={{ backgroundColor: data.report_card_table_header_color }}
                                            >
                                                Avg
                                            </th>
                                        )}
                                    </tr>
                                </thead>
                                <tbody>
                                    {[
                                        { subject: 'Mathematics', score: 85, grade: 'A', avg: 72 },
                                        { subject: 'English', score: 78, grade: 'B', avg: 68 },
                                        { subject: 'Science', score: 92, grade: 'A', avg: 75 },
                                    ].map((row, i) => (
                                        <tr key={i} className={i % 2 === 0 ? 'bg-gray-50' : 'bg-white'}>
                                            <td
                                                className="p-2 text-left"
                                                style={{ borderColor: data.report_card_table_border_color, borderWidth: '1px', borderStyle: 'solid' }}
                                            >
                                                {row.subject}
                                            </td>
                                            <td
                                                className="p-2 text-center"
                                                style={{ borderColor: data.report_card_table_border_color, borderWidth: '1px', borderStyle: 'solid' }}
                                            >
                                                {row.score}
                                            </td>
                                            <td
                                                className="p-2 text-center font-bold"
                                                style={{
                                                    borderColor: data.report_card_table_border_color,
                                                    borderWidth: '1px',
                                                    borderStyle: 'solid',
                                                    color: row.grade === 'A' ? '#22c55e' : '#3b82f6'
                                                }}
                                            >
                                                {row.grade}
                                            </td>
                                            {data.report_card_show_class_average && (
                                                <td
                                                    className="p-2 text-center text-gray-500"
                                                    style={{ borderColor: data.report_card_table_border_color, borderWidth: '1px', borderStyle: 'solid' }}
                                                >
                                                    {row.avg}
                                                </td>
                                            )}
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>

                        {/* Comments Preview */}
                        {(data.report_card_show_teacher_comment || data.report_card_show_principal_comment) && (
                            <div className="space-y-2 text-xs">
                                {data.report_card_show_teacher_comment && (
                                    <div className="bg-blue-50 p-2 rounded">
                                        <span className="font-semibold text-blue-700">Teacher:</span>
                                        <span className="text-gray-600 ml-1">Excellent performance this term!</span>
                                    </div>
                                )}
                                {data.report_card_show_principal_comment && (
                                    <div className="bg-purple-50 p-2 rounded">
                                        <span className="font-semibold text-purple-700">Principal:</span>
                                        <span className="text-gray-600 ml-1">Keep up the good work.</span>
                                    </div>
                                )}
                            </div>
                        )}

                        {/* Footer Disclaimer */}
                        {data.report_card_disclaimer && (
                            <div className="mt-3 pt-2 border-t border-gray-200 text-xs text-gray-400 text-center italic">
                                {data.report_card_disclaimer.length > 80
                                    ? data.report_card_disclaimer.substring(0, 80) + '...'
                                    : data.report_card_disclaimer}
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}

